version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.3-stretch-browsers
    steps:
          - checkout
          - run:
                command: |  # use pipenv to install dependencies
                  sudo pip install pipenv
                  pipenv install
          - run:
                command: |
                  pipenv run pytest

