version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.7.3-stretch-browsers
    steps:
      - checkout
      - run:
          command: |
            sudo pip install pipenv
            pipenv install
      - run:
          command: |
            pipenv run pytest --alluredir=./allure-results
      - run:
          when: always
          command: |
            ls /allure-results
            wget http://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/2.10.0/allure-commandline-2.10.0.zip
            unzip allure-commandline-2.10.0.zip
            ./allure-2.10.0/bin/allure generate ./allure-results -o ./allure-report --clean
      - store_artifacts:
          when: always
          path: allure-report
          destination: report
      - store_test_results:
          when: always
          path: allure-report

