version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.7.3-stretch-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies
      - run:
          command: |
            sudo pip install pipenv
            pipenv install
      - save_cache:
          paths:
            - ./venv
            - ./allure-2.10.0
          key: dependencies
      - run:
          command: |
            pipenv run pytest --alluredir=./allure-results
      - run:
          when: always
          command: |
            ls -l
            f [ ! -f allure-2.10.0 ]; then wget http://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/2.10.0/allure-commandline-2.10.0.zip; unzip allure-commandline-2.10.0.zip fi
            ./allure-2.10.0/bin/allure generate ./allure-results -o ./allure-report --clean
      - store_artifacts:
          when: always
          path: allure-report
          destination: report
      - store_test_results:
          when: always
          path: allure-report

