version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.3-stretch-browsers
    steps:
      - checkout
      - run:
          command: |  # use pipenv to install dependencies
            sudo pip install pipenv
            pipenv install
      - run:
          command: |
            pipenv run pytest --alluredir=./allure-results
  gen_report:
      - run:
          command: |
            sudo apt install unzip wget
            wget http://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/2.10.0/allure-commandline-2.10.0.zip
            unzip allure-commandline-2.10.0.zip
            ./allure-2.10.0/bin/allure generate allure-results -o allure-report --clean
      - store_test_results:
          path: allure-report

